version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: apple_stock_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: apple_stock
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql